; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = servo1_1

[env]
platform = atmelmegaavr
framework = arduino
board = ATtiny1616
board_build.f_cpu = 10000000L
board_hardware.oscillator = internal
build_unflags = 
build_flags = -DARDUINO_AVR_ATtiny1616
upload_protocol = serialupdi
upload_port= /dev/cu.usbmodem61340
;upload_protocol = pickit5_updi 
;upload_port= /dev/cu.usbmodem613402
; upload_flags = "-vx vtarg=3.3"
upload_speed = 57600
monitor_speed = 115200
lib_deps = 
	https://github.com/adafruit/Adafruit_BusIO.git
	; https://github.com/crgmakes/Adafruit_Seesaw.git

[env:relay]
lib_deps = ${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DAQUARIUS=1
	-DAQ_RELAY=1
	-DVERSION=1.0.0
	-I src/relay/

[env:servo1_1]
build_type=debug
lib_deps = ${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DMODULE_VERSION=1.1
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
	-DMODULE_CHANNELS=3
	-DMODULE_ADDR_PIN_0=PIN_PB4
	-DMODULE_ADDR_PIN_1=PIN_PB5
	-DSERVO_1_PIN=PIN_PA7
	-DSERVO_2_PIN=PIN_PA6
	-DSERVO_3_PIN=PIN_PA5
	-DCONFIG_PWM_16BIT=1

	; -I src/servo/
build_src_filter = +<servo/*> +<core/*> -<.git/>

[env:set_fuses]
upload_protocol = ${env:upload_protocol}
upload_flags = 
board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_hardware.updipin = updi
