; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = servo1_1

[env]
extra_scripts = pre:${PROJECT_DIR}/scripts/surpress_register_warnings.py

[env:switch]
lib_deps = ${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DMODULE_VERSION=1.1
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_SWITCH
	-DMODULE_ADDR_PIN_0=PIN_PB4
	-DMODULE_ADDR_PIN_1=PIN_PB5
	-DMODULE_CHANNELS=1
	-DSWITCH_1_PIN=PIN_PA4
	-I src/relay/
build_src_filter = +<switch/*> +<core/*> -<.git/>
platform_packages = platformio/tool-cppcheck@^1.21100.241030

[env:gpio]
lib_deps = ${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DMODULE_VERSION=1.0
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_GPIO
	-DMODULE_ADDR_PIN_0=PIN_PB4
	-DMODULE_ADDR_PIN_1=PIN_PB5
	-DMODULE_CHANNELS=16
	-I src/gpio/
build_src_filter = +<gpio/*> +<core/*> -<.git/>
platform_packages = platformio/tool-cppcheck@^1.21100.241030

[env:servo1_1]
build_type = debug
lib_deps = ${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DMODULE_VERSION=1.1
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
	-DMODULE_ADDR_PIN_0=PIN_PB4
	-DMODULE_ADDR_PIN_1=PIN_PB5
	-DMODULE_CHANNELS=3
	-DSERVO_1_PIN=PIN_PA7
	-DSERVO_2_PIN=PIN_PA6
	-DSERVO_3_PIN=PIN_PA5
	-DCONFIG_PWM_16BIT=1
build_src_filter = +<servo/*> +<core/*> -<.git/>
upload_protocol = pickit5_updi
upload_command = /Users/tsasala/Downloads/avrdude8.1/bin/avrdude -C /Users/tsasala/Downloads/avrdude8.1/etc/avrdude.conf -c pickit5_updi -pATtiny1616 -Pusbmodem41302 -U flash:w:$SOURCE:i
platform_packages = platformio/tool-cppcheck@^1.21100.241030

[env:set_fuses]
upload_protocol = ${env:upload_protocol}
upload_flags = 
board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_hardware.updipin = updi
platform_packages = platformio/tool-cppcheck@^1.21100.241030

[env:nucleo_c031c6]
platform = ststm32
board = nucleo_c031c6
platform_packages = 
	tool-openocd@symlink://packages/xpack-openocd-0.12.0-7
	platformio/tool-cppcheck@^1.21100.241030
framework = arduino
upload_protocol = stlink
lib_deps = 
	https://github.com/adafruit/Adafruit_BusIO.git
build_type = debug
build_flags = 
	${env.build_flags}
	-DMODULE_VERSION=1.1
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
	-DMODULE_ADDR_PIN_0=PB_4
	-DMODULE_ADDR_PIN_1=PB_5
	-DMODULE_CHANNELS=3
	-DSERVO_1_PIN=PA_7
	-DSERVO_2_PIN=PA_6
	-DSERVO_3_PIN=PA_5
	-DSERVO_4_PIN=PB_0
	-DCONFIG_PWM_16BIT=1
	-D HAL_ADC_MODULE_DISABLED
	-D HAL_RTC_MODULE_DISABLED
	-D HAL_DAC_MODULE_DISABLED
	-D HAL_EXTI_MODULE_DISABLED
	-DHW_SERIAL_NONE
build_src_filter = +<servo/*> +<core/*> -<.git/>
