; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = servo_v10

[env]
extra_scripts = 
	pre:${PROJECT_DIR}/scripts/surpress_register_warnings.py

[env:nucleo_c031c6]
build_type = debug
platform = ststm32
board = nucleo_c031c6
platform_packages = 
	tool-openocd@symlink://packages/xpack-openocd-0.12.0-7
	platformio/tool-cppcheck@^1.21100.241030
framework = arduino
upload_protocol = stlink
lib_deps = 
	; https://github.com/adafruit/Adafruit_BusIO.git
build_flags = 
	${env.build_flags}
	-Os
	-specs=nano.specs
	-DMODULE_VERSION=0
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
	-DMODULE_ADDR_PIN_0=PB_4
	-DMODULE_ADDR_PIN_1=PB_5
	-DMODULE_I2C_SCL=PB8
	-DMODULE_I2C_SDA=PB9
	-DMODULE_CHANNELS=4
	-DIO_PINS='{PA6, PA7, PB0, PC7}'
	-DMODULE_LED_CHANNELS=0
	-DLED_PINS='{}'
	-DLED_STATUS_PIN=PA5
	-DMODULE_RX_PIN=PA3
	-DMODULE_TX_PIN=PA2
	-DCONFIG_UART_DEBUG=1
	-D HAL_SPI_MODULE_DISABLED
	-D HAL_ADC_MODULE_DISABLED
	-D HAL_RTC_MODULE_DISABLED
	-D HAL_DAC_MODULE_DISABLED
	-D HAL_EXTI_MODULE_DISABLED
	; -DHW_SERIAL_NONE
build_src_filter = +<servo/*> +<core/*> -<.git/>
monitor_dtr = 1
monitor_rts = 1
monitor_port = /dev/cu./dev/cu.usbmodem8434203
monitor_speed = 115200

[env:io_v10]
; IO module v1.0 uses STM32C092GCU6
build_type = debug
platform = ststm32
board = stm32c092gcu6
board_build.ldscript = boards/stm32c092gcu6_ldscript.ld
platform_packages = 
	tool-openocd@symlink://packages/xpack-openocd-0.12.0-7
	platformio/tool-cppcheck@^1.21100.241030
framework = arduino
; upload_protocol = stlink
upload_protocol = custom
upload_command = "${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/bin/openocd" -d2 -s "${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/openocd/scripts" -s "${PROJECT_DIR}/openocd" -f "${PROJECT_DIR}/openocd/stm32c092gcu6.cfg" -c "program {$SOURCE} verify reset; shutdown;"
debug_tool = custom
debug_server =
    ${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/bin/openocd
    -d2
    -s ${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/openocd/scripts
    -s ${PROJECT_DIR}/openocd
    -f stm32c092gcu6.cfg
lib_deps = 
build_flags = 
	-Os
	-specs=nano.specs
	-DMODULE_VERSION=10
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDR_PIN_0=PB3
	-DMODULE_ADDR_PIN_1=PB4
	-DMODULE_I2C_SCL=PB8
	-DMODULE_I2C_SDA=PB7
	-DMODULE_CHANNELS=4
	-DIO_PINS='{PB1, PB0, PA7, PA6}'
	-DMODULE_LED_CHANNELS=4
	-DLED_PINS='{PA5, PA4, PA3, PA2}'
	-DLED_STATUS_PIN=PA2
	-DMODULE_RX_PIN=PA1
	-DMODULE_TX_PIN=PA0
	-DCONFIG_UART_DEBUG=0
	-D HAL_SPI_MODULE_DISABLED
	-D HAL_ADC_MODULE_DISABLED
	-D HAL_RTC_MODULE_DISABLED
	-D HAL_DAC_MODULE_DISABLED
	-D HAL_EXTI_MODULE_DISABLED
monitor_dtr = 1
monitor_rts = 1
monitor_port = /dev/cu./dev/cu.usbmodem8434203
monitor_speed = 115200

[env:io_v11]
; IO module v1.1 uses STM32C092GCU6
build_type = debug
platform = ststm32
board = stm32c092gcu6
board_build.ldscript = boards/stm32c092gcu6_ldscript.ld
platform_packages = 
	tool-openocd@symlink://packages/xpack-openocd-0.12.0-7
	platformio/tool-cppcheck@^1.21100.241030
framework = arduino
;upload_protocol = stlink
upload_protocol = custom
upload_command = "${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/bin/openocd" -d2 -s "${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/openocd/scripts" -s "${PROJECT_DIR}/openocd" -f "${PROJECT_DIR}/openocd/stm32c092gcu6.cfg" -c "program {$SOURCE} verify reset; shutdown;"
debug_tool = custom
debug_server =
    ${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/bin/openocd
    -d2
    -s ${PROJECT_DIR}/packages/xpack-openocd-0.12.0-7/openocd/scripts
    -s ${PROJECT_DIR}/openocd
    -f stm32c092gcu6.cfg
lib_deps = 
build_flags = 
	-Os
	-specs=nano.specs
	-DMODULE_VERSION=11
	-DMODULE_HW_ID=0x88
	-DMODULE_ADDR_PIN_0=PB3
	-DMODULE_ADDR_PIN_1=PB4
	-DMODULE_I2C_SCL=PB8
	-DMODULE_I2C_SDA=PB7
	-DMODULE_CHANNELS=4
	-DIO_PINS='{PB1, PB0, PA7, PA6}'
	-DMODULE_LED_CHANNELS=4
	-DLED_PINS='{PA5, PA4, PA3, PA2}'
	-DLED_STATUS_PIN=PA15
	-DMODULE_RX_PIN=PA1
	-DMODULE_TX_PIN=PA0
	-DCONFIG_UART_DEBUG=1
	-D HAL_SPI_MODULE_DISABLED
	-D HAL_ADC_MODULE_DISABLED
	-D HAL_RTC_MODULE_DISABLED
	-D HAL_DAC_MODULE_DISABLED
	-D HAL_EXTI_MODULE_DISABLED
monitor_dtr = 1
monitor_rts = 1
monitor_port = /dev/cu./dev/cu.usbmodem8434203
monitor_speed = 115200

[env:servo_v10]
extends = env:io_v10
build_flags = 
	${env:io_v10.build_flags}
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
build_src_filter = +<servo/*> +<core/*> -<.git/>

[env:servo_v11]
extends = env:io_v11
build_flags = 
	${env:io_v11.build_flags}
	-DMODULE_ADDRESS=MODULE_ADDRESS_SERVO
build_src_filter = +<servo/*> +<core/*> -<.git/>

[env:current_v10]
extends = env:io_v10
build_flags = 
	${env:io_v10.build_flags}
	-DMODULE_ADDRESS=MODULE_ADDRESS_CURRENT
build_src_filter = +<current/*> +<core/*> -<.git/>

[env:current_v11]
extends = env:io_v11
build_flags = 
	${env:io_v11.build_flags}
	-DMODULE_ADDRESS=MODULE_ADDRESS_CURRENT
build_src_filter = +<current/*> +<core/*> -<.git/>
