/**
 * @brief Defines attributes about the modules
 * @file ModuleHardware.h
 * @date June 15, 2025
 * @author cyberreefguru
 */
#pragma once

#define MODULE_SERVO_PRODUCT_CODE 0xAA40
#define MODULE_MOTOR_PRODUCT_CODE 0xAA41
#define MODULE_SWITCH_PRODUCT_CODE 0xAA42
#define MODULE_RELAY_PRODUCT_CODE 0xAA42
#define MODULE_IR_PRODUCT_CODE 0xAA43
#define MODULE_RF_PRODUCT_CODE 0xAA44
#define MODULE_CURRENT_PRODUCT_CODE 0xAA45
#define MODULE_ENVIRONMENT_PRODUCT_CODE 0xAA46
#define MODULE_PARTICLE_PRODUCT_CODE 0xAA47

#define MODULE_SERVO_ADDRESS 0x40
#define MODULE_MOTOR_ADDRESS 0x41
#define MODULE_SWITCH_ADDRESS 0x42
#define MODULE_RELAY_ADDRESS 0x42
#define MODULE_IR_ADDRESS 0x43
#define MODULE_RF_ADDRESS 0x44
#define MODULE_CURRENT_ADDRESS 0x45
#define MODULE_ENVIRONMENT_ADDRESS 0x46
#define MODULE_PARTICLE_ADDRESS 0x47
